name: tencent_ad_example
description: 欢迎指正
publish_to: 'https://pub.dev/packages/tencent_ad' 
version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tencent_ad:
    path: ../
  cupertino_icons: 
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  
  assets:
    - assets/svg/

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
